/* Cable: CMake Bootstrap Library.
 * Copyright 2018 Pawel Bylica.
 * Licensed under the Apache License, Version 2.0. See the LICENSE file.
 */

/* Generated by Cable Build Info on 2019-03-12T16:56:15. Do not modify directly. */

#include "buildinfo.h"

const struct buildinfo* brcd_get_buildinfo()
{
    static const struct buildinfo buildinfo = {
        .project_name = "brcd",
        .project_version = "1.5.0-alpha.6-129+commit.e9add178",
        .project_name_with_version = "brcd-1.5.0-alpha.6-129+commit.e9add178",
        .git_commit_hash = "e9add178bfd523d655833b3c3e1bd092d12ef0e4",
        .system_name = "darwin",
        .system_processor = "x86_64",
        .compiler_id = "appleclang",
        .compiler_version = "10.0.0.10001044",
        .build_type = "relwithdebinfo",
    };
    return &buildinfo;
}
